# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_hdf5gui(object):
    def setupUi(self, hdf5gui):
        hdf5gui.setObjectName("hdf5gui")
        hdf5gui.resize(702, 438)
        self.centralwidget = QtWidgets.QWidget(hdf5gui)
        self.centralwidget.setObjectName("centralwidget")
        self.input_file_gbox = QtWidgets.QGroupBox(self.centralwidget)
        self.input_file_gbox.setGeometry(QtCore.QRect(10, 10, 681, 151))
        self.input_file_gbox.setObjectName("input_file_gbox")
        self.file_list = FileDragDropListWidget(self.input_file_gbox)
        self.file_list.setGeometry(QtCore.QRect(10, 30, 581, 111))
        self.file_list.setAcceptDrops(True)
        self.file_list.setDragEnabled(True)
        self.file_list.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.file_list.setMovement(QtWidgets.QListView.Snap)
        self.file_list.setObjectName("file_list")
        self.file_up = QtWidgets.QPushButton(self.input_file_gbox)
        self.file_up.setGeometry(QtCore.QRect(600, 30, 75, 21))
        self.file_up.setObjectName("file_up")
        self.file_down = QtWidgets.QPushButton(self.input_file_gbox)
        self.file_down.setGeometry(QtCore.QRect(600, 60, 75, 21))
        self.file_down.setObjectName("file_down")
        self.delete_button = QtWidgets.QPushButton(self.input_file_gbox)
        self.delete_button.setGeometry(QtCore.QRect(600, 90, 75, 21))
        self.delete_button.setObjectName("delete_button")
        self.load_button = QtWidgets.QPushButton(self.input_file_gbox)
        self.load_button.setGeometry(QtCore.QRect(600, 120, 75, 21))
        self.load_button.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.load_button.setObjectName("load_button")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 170, 681, 61))
        self.groupBox.setObjectName("groupBox")
        self.save_folder = QtWidgets.QLineEdit(self.groupBox)
        self.save_folder.setGeometry(QtCore.QRect(10, 30, 581, 20))
        self.save_folder.setObjectName("save_folder")
        self.folder_browser = QtWidgets.QPushButton(self.groupBox)
        self.folder_browser.setGeometry(QtCore.QRect(600, 30, 75, 23))
        self.folder_browser.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.folder_browser.setObjectName("folder_browser")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 240, 201, 171))
        self.groupBox_2.setObjectName("groupBox_2")
        self.average_check = QtWidgets.QCheckBox(self.groupBox_2)
        self.average_check.setGeometry(QtCore.QRect(20, 30, 171, 21))
        self.average_check.setChecked(True)
        self.average_check.setObjectName("average_check")
        self.metadata_check = QtWidgets.QCheckBox(self.groupBox_2)
        self.metadata_check.setGeometry(QtCore.QRect(20, 60, 91, 17))
        self.metadata_check.setChecked(True)
        self.metadata_check.setObjectName("metadata_check")
        self.sweeps_check = QtWidgets.QCheckBox(self.groupBox_2)
        self.sweeps_check.setGeometry(QtCore.QRect(20, 90, 181, 17))
        self.sweeps_check.setChecked(True)
        self.sweeps_check.setObjectName("sweeps_check")
        self.convert_button = QtWidgets.QPushButton(self.groupBox_2)
        self.convert_button.setGeometry(QtCore.QRect(20, 120, 161, 41))
        self.convert_button.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.convert_button.setObjectName("convert_button")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(220, 240, 471, 171))
        self.groupBox_3.setObjectName("groupBox_3")
        self.console = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.console.setGeometry(QtCore.QRect(10, 30, 451, 131))
        self.console.setReadOnly(True)
        self.console.setObjectName("console")
        hdf5gui.setCentralWidget(self.centralwidget)
        self.status_bar = QtWidgets.QStatusBar(hdf5gui)
        self.status_bar.setObjectName("status_bar")
        hdf5gui.setStatusBar(self.status_bar)

        self.retranslateUi(hdf5gui)
        QtCore.QMetaObject.connectSlotsByName(hdf5gui)

    def retranslateUi(self, hdf5gui):
        _translate = QtCore.QCoreApplication.translate
        hdf5gui.setWindowTitle(_translate("hdf5gui", "HDF5 Conversion Tool"))
        self.input_file_gbox.setTitle(_translate("hdf5gui", "drag and drop hdf5 files, then press load all"))
        self.file_up.setText(_translate("hdf5gui", "move up"))
        self.file_down.setText(_translate("hdf5gui", "move down"))
        self.delete_button.setText(_translate("hdf5gui", "delete"))
        self.load_button.setText(_translate("hdf5gui", "load all"))
        self.groupBox.setTitle(_translate("hdf5gui", "choose a folder for the extracted data to be saved in"))
        self.folder_browser.setText(_translate("hdf5gui", "Browse"))
        self.groupBox_2.setTitle(_translate("hdf5gui", "choose types of data to save"))
        self.average_check.setText(_translate("hdf5gui", "averaged matrix"))
        self.metadata_check.setText(_translate("hdf5gui", "metadata"))
        self.sweeps_check.setText(_translate("hdf5gui", "matrix for each sweep"))
        self.convert_button.setText(_translate("hdf5gui", "convert"))
        self.groupBox_3.setTitle(_translate("hdf5gui", "information"))

from filedragdroplistwidget import FileDragDropListWidget
